var __abilityDescriptions = {};
(function(){
    var data = [
        { "name": "Air Lock", "description": "Eliminates the effects of weather." },
        { "name": "Arena Trap", "description": "Prevents the foe from fleeing." },
        { "name": "Battle Armor", "description": "The Pokémon is protected against critical hits." },
        { "name": "Blaze", "description": "Powers up Fire-type moves in a pinch." },
        { "name": "Chlorophyll", "description": "Boosts the Pokémon's Speed in sunshine." },
        { "name": "Clear Body", "description": "Prevents other Pokémon from lowering its stats." },
        { "name": "Cloud Nine", "description": "Eliminates the effects of weather." },
        { "name": "Color Change", "description": "Changes the Pokémon's type to the foe's move." },
        { "name": "Compound Eyes", "description": "The Pokémon's accuracy is boosted." },
        { "name": "Cute Charm", "description": "Contact with the Pokémon may cause infatuation." },
        { "name": "Damp", "description": "Prevents the use of self-destructing moves." },
        { "name": "Drizzle", "description": "The Pokémon makes it rain when it enters a battle." },
        { "name": "Drought", "description": "Turns the sunlight harsh when the Pokémon enters a battle." },
        { "name": "Early Bird", "description": "The Pokémon awakens quickly from sleep." },
        { "name": "Effect Spore", "description": "Contact may poison or cause paralysis or sleep." },
        { "name": "Flame Body", "description": "Contact with the Pokémon may burn the attacker." },
        { "name": "Flash Fire", "description": "It powers up Fire-type moves if it's hit by one." },
        { "name": "Forecast", "description": "Castform transforms with the weather." },
        { "name": "Guts", "description": "Boosts Attack if there is a status problem." },
        { "name": "Huge Power", "description": "Raises the Pokémon's Attack stat." },
        { "name": "Hustle", "description": "Boosts the Attack stat, but lowers accuracy." },
        { "name": "Hyper Cutter", "description": "Prevents other Pokémon from lowering Attack stat." },
        { "name": "Illuminate", "description": "Raises the likelihood of meeting wild Pokémon." },
        { "name": "Immunity", "description": "Prevents the Pokémon from getting poisoned." },
        { "name": "Inner Focus", "description": "The Pokémon is protected from flinching." },
        { "name": "Insomnia", "description": "Prevents the Pokémon from falling asleep." },
        { "name": "Intimidate", "description": "Lowers the foe's Attack stat." },
        { "name": "Keen Eye", "description": "Prevents other Pokémon from lowering accuracy." },
        { "name": "Levitate", "description": "Gives immunity to Ground type moves." },
        { "name": "Lightning Rod", "description": "Draws in all Electric-type moves to up Sp. Attack." },
        { "name": "Limber", "description": "The Pokémon is protected from paralysis." },
        { "name": "Liquid Ooze", "description": "Damages attackers using any draining move." },
        { "name": "Magma Armor", "description": "Prevents the Pokémon from becoming frozen." },
        { "name": "Magnet Pull", "description": "Prevents Steel-type Pokémon from escaping." },
        { "name": "Marvel Scale", "description": "Ups Defense if there is a status problem." },
        { "name": "Minus", "description": "Ups Sp. Atk if another Pokémon has Plus or Minus." },
        { "name": "Natural Cure", "description": "All status problems heal when it switches out." },
        { "name": "Oblivious", "description": "Prevents it from becoming infatuated." },
        { "name": "Overgrow", "description": "Powers up Grass-type moves in a pinch." },
        { "name": "Own Tempo", "description": "Prevents the Pokémon from becoming confused." },
        { "name": "Pickup", "description": "The Pokémon may pick up items." },
        { "name": "Plus", "description": "Ups Sp. Atk if another Pokémon has Plus or Minus." },
        { "name": "Poison Point", "description": "Contact with the Pokémon may poison the attacker." },
        { "name": "Pressure", "description": "The Pokémon raises the foe's PP usage." },
        { "name": "Pure Power", "description": "Raises the Pokémon's Attack stat." },
        { "name": "Rain Dish", "description": "The Pokémon gradually regains HP in rain." },
        { "name": "Rock Head", "description": "Protects the Pokémon from recoil damage." },
        { "name": "Rough Skin", "description": "Inflicts damage to the attacker on contact." },
        { "name": "Run Away", "description": "Enables a sure getaway from wild Pokémon." },
        { "name": "Sand Stream", "description": "The Pokémon summons a sandstorm in battle." },
        { "name": "Sand Veil", "description": "Boosts the Pokémon's evasion in a sandstorm." },
        { "name": "Serene Grace", "description": "Boosts the likelihood of added effects appearing." },
        { "name": "Shadow Tag", "description": "Prevents the foe from escaping." },
        { "name": "Shed Skin", "description": "The Pokémon may heal its own status problems." },
        { "name": "Shell Armor", "description": "The Pokémon is protected against critical hits." },
        { "name": "Shield Dust", "description": "Blocks the added effects of attacks taken." },
        { "name": "Soundproof", "description": "Gives immunity to sound-based moves." },
        { "name": "Speed Boost", "description": "Its Speed stat is gradually boosted." },
        { "name": "Static", "description": "Contact with the Pokémon may cause paralysis." },
        { "name": "Stench", "description": "The stench may cause the target to flinch." },
        { "name": "Sticky Hold", "description": "Protects the Pokémon from item theft." },
        { "name": "Sturdy", "description": "It cannot be knocked out with one hit." },
        { "name": "Suction Cups", "description": "Negates all moves that force switching out." },
        { "name": "Swarm", "description": "Powers up Bug-type moves in a pinch." },
        { "name": "Swift Swim", "description": "Boosts the Pokémon's Speed in rain." },
        { "name": "Synchronize", "description": "Passes a burn, poison, or paralysis to the foe." },
        { "name": "Thick Fat", "description": "Ups resistance to Fire- and Ice-type moves." },
        { "name": "Torrent", "description": "Powers up Water-type moves in a pinch." },
        { "name": "Trace", "description": "The Pokémon copies a foe's Ability." },
        { "name": "Truant", "description": "Pokémon can't attack on consecutive turns." },
        { "name": "Vital Spirit", "description": "Prevents the Pokémon from falling asleep." },
        { "name": "Volt Absorb", "description": "Restores HP if hit by an Electric-type move." },
        { "name": "Water Absorb", "description": "Restores HP if hit by a Water-type move." },
        { "name": "Water Veil", "description": "Prevents the Pokémon from getting a burn." },
        { "name": "White Smoke", "description": "Prevents other Pokémon from lowering its stats." },
        { "name": "Wonder Guard", "description": "Only supereffective moves will hit." }
    ];
    data.forEach(function(a){ __abilityDescriptions[a.name] = a.description; });
})();
